<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php 
$value = '';
if($block->getCustomer()  && $block->getCustomer()->getCustomAttribute('linkedin_profile')){
    $value = $block->getCustomer()->getCustomAttribute('linkedin_profile')->getValue();
}
?>
<div class="field linkedin required">
    <label for="regulation" class="label"><span><?php /* @escapeNotVerified */
            echo __('Linkedin Profile') ?></span></label>
    <div class="control">
        <input type="text" name="linkedin_profile" id="linkedin_profile" title="<?php /* @escapeNotVerified */
        echo __('Linkedin Profile') ?>" class="input-text validate-url validate-length maximum-length-250"
         value="<?php echo $block->escapeHtml($value) ?>" >
    </div>
</div>
